### ISSUE TITLE
archlinux-tweak-tool wont load

### ISSUE THREAD

**Issue by bknightInfo** [erikdubois/arcolinux-nemesis#4]
archlinux-tweak-tool with a fresh version of archlinux

arcolinux-nemesis]$ archlinux-tweak-tool
Traceback (most recent call last):
  File "/usr/share/archlinux-tweak-tool/archlinux-tweak-tool.py", line 16, in <module>
    import autostart
  File "/usr/share/archlinux-tweak-tool/autostart.py", line 4, in <module>
    import Functions as fn
  File "/usr/share/archlinux-tweak-tool/Functions.py", line 16, in <module>
    gi.require_version('Gtk', '3.0')
AttributeError: module 'gi' has no attribute 'require_version'

**Comment by erikdubois** [comment]
why are you reporting here?
We are following this tool on discord.
we need to know on what this occurs
our communication ends here on github
